const vehicle = {
 'cycle-urban-terrain-rogue': {
    name: 'Urban Terrain Rogue',
    companyName: 'Urban Terrain',
    tagline: 'Built for city commuting with confidence on rough roads.',
    fuel: 'Air',
    seats: 1,
    gears: '21-speed',
    pricePerHour: 20,
    pricePerDay: 120,
    description: 'Suitable for city rides + mild off-road.',
    conditions: 'Damage to gears/brakes will be charged; return clean.',
    image:'/image/cycles/Urban Terrain Rogue/full_cycle.jpg'
  },
  'cycle-leader-lady-star-breeze-26t':{
    name: 'Leader Lady Star Breeze 26T',
    tagline: "Comfortable and easy city cycling designed for daily rides.",
    companyName:'Leader',
    fuel: 'Air',
    seats: 1,
    gears: 'Single-speed',
    pricePerHour: 15,
    pricePerDay: 100,
    description: 'Easy for short city commutes.',
    conditions: 'Basket misuse not allowed.',
    image:"image/cycles/Leader Lady Star Breeze 26T/full.jpg"
  },
  'cycle-rally-gold-popular':{
    name: 'Rally Gold Rally Popular',
    companyName:'Rally',
    tagline: 'A simple, durable cycle for everyday urban use.',
    fuel: 'Air',
    seats: 1,
    gears: 'Single-speed',
    pricePerHour: 15,
    pricePerDay: 100,
    description: 'Basic cycle for short rides.',
    conditions: 'Avoid riding on rough trails.',
    image:"image/cycles/ralley gold rally popular/full.jpg"
  },
  'cycle-leader-xtreme-mtb-26t-ibc':{
    name: 'Leader Xtreme MTB 26T IBC Mountain',
    companyName:'Leader',
    fuel: 'Air',
    seats: 1,
    gears: '18-speed',
    pricePerHour: 20,
    pricePerDay: 130,
    description: 'Good for trails and uneven roads.',
    conditions: 'Heavy off-roading damage chargeable.',
    tagline: 'Strong mountain bike made for trails and rough terrain.',
    image:"image/cycles/Leader Xtreme MTB 26T IBC Mountain/full.jpg"
  },
  'cycle-leader-beast-26t-ibc':{
    name: 'Leader Beast 26T IBC Premium Rigid City',
    companyName:'Leader',
    tagline: 'A sturdy city cycle built for smooth and reliable rides.',
    fuel: 'Air',
    seats: 1,
    gears: 'Single-speed',
    specifications: 'Rigid fork, wide tyres',
    pricePerHour: 18,
    pricePerDay: 120,
    description: 'Strong frame, ideal for city + slightly rough roads.',
    conditions: 'Tyre damage will be billed.',
    image:"image/cycles/Leader Beast 26T IBC Premium Rigid City/full.jpg"
  },
  'bike-honda-shine-125': {
    name: 'Honda Shine 125',
    fuel: 'Petrol',
    seats: 2,
    gears: '5-speed',
    specifications: '124cc, CBS, smooth suspension',
    pricePerHour: 60,
    pricePerDay: 450,
    description: 'Best for city use, reliable & low fuel cost.',
    conditions: 'No harsh acceleration, return with same fuel.',
    companyName: "Honda",
    tagline: "Reliable commuter bike with excellent mileage and comfort.",
    image:"image/bikes/shine/full.webp"
  },
  'bike-ather-450x': {
    name: 'Ather 450X',
    fuel: 'Electric',
    seats: 2,
    gears: 'Automatic',
    specifications: '6 kW motor, fast charging',
    pricePerHour: 70,
    pricePerDay: 550,
    description: 'Silent, quick, ideal for urban trips.',
    conditions: 'Return with minimum 40% battery.',
    companyName: "Ather Energy",
    tagline: "High-performance electric scooter with smart technology.",
    image:"image/bikes/Ather 450X/450x450xleftfrontthreequarter.webp"
  },
  'bike-bajaj-pulsar-150': {
    name: 'Bajaj Pulsar 150',
    fuel: 'Petrol',
    seats: 2,
    gears: '5-speed',
    specifications: '149cc, strong mid-range',
    pricePerHour: 80,
    pricePerDay: 600,
    description: 'Good for mixed city/highway.',
    conditions: 'No stunt riding.',
    companyName: "Bajaj",
    tagline: "Sporty performance bike ideal for city and highway rides.",
    image:"image/bikes/Bajaj Pulsar 150/full.webp"
  },
  'bike-re-classic-350': {
    name: 'Royal Enfield Classic 350',
    fuel: 'Petrol',
    seats: 2,
    gears: '5-speed',
    specifications: '349cc, ABS, high torque',
    pricePerHour: 120,
    pricePerDay: 900,
    description: 'Premium feel, great for long rides.',
    conditions: 'Full inspection required on return.',
    companyName: "Royal Enfield",
    tagline: "Timeless cruiser built for relaxed long rides.",
    image:"image/bikes/Royal Enfield Classic 350/classic350classicrightfrontthreequarter.webp" 
  },
  'bike-re-himalayan':{
    name: 'Royal Enfield Himalayan',
    fuel: 'Petrol',
    seats: 2,
    gears: '5-speed',
    specifications: '411cc, long-travel suspension',
    pricePerHour: 140,
    pricePerDay: 1100,
    description: 'Designed for rough roads & touring.',
    conditions: 'Off-road damage chargeable.',
    companyName: "Royal Enfield",
    tagline: "Adventure motorcycle made for highways and off-road travel.",
    image:"image/bikes/Royal Enfield Himalayan/himalayan450himalayanrightfrontthreequarter.webp"
  },
  'bike-tvs-apache-rtr-160':{
    name: 'TVS Apache RTR 160',
    fuel: 'Petrol',
    seats: 2,
    gears: '5-speed',
    specifications: '159cc, aggressive pickup',
    pricePerHour: 70,
    pricePerDay: 500,
    description: 'Quick and sporty for city.',
    conditions: 'Speed limit applies.',
    companyName: "TVS",
    tagline: "Performance-focused bike with sharp handling and power.",
    image:"image/bikes/TVS Apache RTR 160/tvsapachertr160rightfrontthreequarter.webp"
  },
  'bike-tvs-iqube':{
    name: 'TVS iQube',
    fuel: 'Electric',
    seats: 2,
    gears: 'Automatic',
    specifications: '4.4 kW motor, TFT display',
    pricePerHour: 65,
    pricePerDay: 500,
    description: 'Smooth EV for daily errands.',
    conditions: 'Return with charger + 40% battery.',
    companyName: "TVS",
    tagline: "Practical electric scooter designed for urban commuting.",
    image:"image/bikes/TVS iQube/iqubeiquberightfrontthreequarter.webp"
  },
  'bike-tvs-star-city-plus':{
    name: 'TVS Star City Plus',
    fuel: 'Petrol',
    seats: 2,
    gears: '4-speed',
    specifications: '110cc, Eco-thrust engine',
    pricePerHour: 55,
    pricePerDay: 400,
    description: 'Low running cost, good for students.',
    conditions: 'Moderate load only.',
    companyName: "TVS",
    tagline: "Fuel-efficient commuter bike for everyday city travel.",
    image:"image/bikes/TVS Star City Plus/rightfrontthreequarter.webp"
  },
  'car-honda-city':{
    name: 'Honda City',
    fuel: 'Petrol',
    seats: 5,
    gears: 'Manual/Automatic',
    pricePerHour: 250,
    pricePerDay: 2000,
    description: 'Comfortable premium sedan.',
    conditions: 'No smoking, return clean.',
    companyName: "Honda",
    tagline: "Premium sedan offering comfort and smooth highway performance.",
    image:"image/car/Honda City/full.webp"
  },
  'car-hyundai-grand-i10-nios':{
    name: 'Hyundai Grand i10 Nios',
    fuel: 'Petrol',
    seats: 5,
    gears: 'Manual/Automatic',
    pricePerHour: 180,
    pricePerDay: 1400,
    description: 'Best for city trips.',
    conditions: 'KM limit per day (~150 km).',
    companyName: "Hyundai",
    tagline: "Compact hatchback perfect for city driving.",
    image:"image/car/Hyundai Grand i10 Nios/full.webp"
  },
  'car-hyundai-i20':{
    name: 'Hyundai i20',
    fuel: 'Petrol',
    seats: 5,
    gears: 'Manual/Automatic',
    pricePerHour: 220,
    pricePerDay: 1700,
    description: 'Spacious & feature-rich.',
    conditions: 'No off-road use.',
    companyName: "Hyundai",
    tagline: "Stylish premium hatchback with advanced features."
  },
 'car-hyundai-verna':{
    name: 'Hyundai Verna',
    fuel: 'Petrol',
    seats: 5,
    gears: 'Manual/Automatic',
    pricePerHour: 260,
    pricePerDay: 2100,
    description: 'Stylish sedan with strong performance.',
    conditions: 'Security deposit higher.',
    companyName: "Hyundai",
    tagline: "Sleek sedan delivering comfort and strong performance.",
    image:"image/car/Hyundai Verna/full.webp"
  },
  'car-mahindra-bolero':{
    name: 'Mahindra Bolero',
    type: 'SUV',
    fuel: 'Diesel',
    seats: 7,
    gears: 'Manual',
    pricePerHour: 300,
    pricePerDay: 2200,
    description: 'Rugged, rural-friendly vehicle.',
    conditions: 'High cleaning charges if returned dirty.',
    companyName: "Mahindra",
    tagline: "Tough utility vehicle built for rough roads and heavy use.",
    image:"image/car/Mahindra Bolero/full.webp"
  },
  'car-maruti-ertiga':{
    name: 'Maruti Ertiga',
    fuel: 'Petrol/CNG',
    seats: 7,
    gears: 'Manual/Automatic',
    pricePerHour: 280,
    pricePerDay: 2000,
    description: 'Best family / group rental.',
    conditions: 'Extra charge for CNG refilling mismatch.',
    companyName: "Maruti Suzuki",
    tagline: "Spacious family MPV ideal for group travel.",
    image:"image/car/Maruti Ertiga/ertigaertigarightfrontthreequarter.webp"
  },
  'car-maruti-dzire':{
    name: 'Maruti Suzuki Dzire',
    fuel: 'Petrol',
    seats: 5,
    gears: 'Manual/Automatic',
    pricePerHour: 200,
    pricePerDay: 1500,
    description: 'Cheap to run, good for city.',
    conditions: 'No long-hill driving.',
    companyName: "Maruti Suzuki",
    tagline: "Comfortable compact sedan with excellent fuel efficiency.",
    image:"image/car/Maruti Suzuki Dzire/full.webp"
  },
  'car-maruti-swift':{
    name: 'Maruti Suzuki Swift',
    fuel: 'Petrol',
    seats: 5,
    gears: 'Manual/Automatic',
    pricePerHour: 190,
    pricePerDay: 1400,
    description: 'Fun-to-drive, light and efficient.',
    conditions: 'KM limit applies.',
    companyName: "Maruti Suzuki",
    tagline: "Fun-to-drive hatchback with agile city handling.",
    image:"image/car/Maruti Suzuki Swift/full.webp"
  },
  'car-mg-zs-ev':{
    name: 'MG ZS EV',
    fuel: 'Electric',
    seats: 5,
    gears: 'Automatic',
    pricePerHour: 350,
    pricePerDay: 2600,
    description: 'Premium EV with strong range.',
    conditions: 'Must return with ≥50% charge.',
    companyName: "MG Motor",
    tagline: "Electric SUV offering comfort with zero emissions.",
    image:"image/car/MG ZS EV/full.webp"
  },
  'car-tata-tiago-ev':{
    name: 'Tata Tiago EV',
    fuel: 'Electric',
    seats: 5,
    gears: 'Automatic',
    pricePerHour: 220,
    pricePerDay: 1600,
    description: 'Affordable EV for city drives.',
    conditions: 'Battery health check at return.',
    companyName: "Tata Motors",
    tagline: "Affordable electric hatchback for city commuting.",
    image:"image/car/Tata Tiago EV/full.webp"
  },
  'car-toyota-hyryder':{
    name: 'Toyota Hyryder',
    fuel: 'Petrol/Hybrid',
    seats: 5,
    gears: 'Automatic',
    pricePerHour: 330,
    pricePerDay: 2500,
    description: 'High fuel efficiency + comfort.',
    conditions: 'No towing allowed.',
    companyName: "Toyota",
    tagline: "Hybrid SUV combining efficiency with modern comfort.",
    image:"image/car/Toyota Hyryder/full.webp"
  },
  'car-toyota-innova-crysta':{
    name: 'Toyota Innova Crysta',
    fuel: 'Diesel',
    seats: 7,
    gears: 'Manual/Automatic',
    pricePerHour: 380,
    pricePerDay: 3000,
    description: 'Long-distance king, best for family trips.',
    conditions: 'High security deposit.',
    companyName: "Toyota",
    tagline: "Premium MPV built for long and comfortable journeys.",
    image:"image/car/Toyota Innova Crysta/full.webp"
  },
  'car-maruti-suzuki-baleno': {
  name: 'Maruti Suzuki Baleno',
  fuel: 'Petrol',
  seats: 5,
  gears: 'Manual/Automatic',
  pricePerHour: 280,
  pricePerDay: 2000,
  description: 'Comfortable premium hatchback, ideal for city and highway drives.',
  conditions: 'Fuel not included; return with same fuel level.',
  companyName: "Maruti Suzuki",
  tagline: "Smooth and spacious hatchback ideal for city and highway drives.",
  image:"image/car/Maruti Suzuki Baleno/full.webp" 
}

}

